version: '3.9'

volumes:
  storage:


services:
  controlacontas:
    build:
      context: .
      dockerfile: ./docker/controlacontas/Dockerfile
    container_name: controlacontas_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./controlacontas:/usr/src/controlacontas
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
      - cache
      - email

  database:
    image: postgres:14-alpine
    container_name: controlacontas_database
    restart: always
    volumes:
      - storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=controlacontas
      - POSTGRES_USER=controlacontas
      - POSTGRES_PASSWORD=controlacontas

  cache:
    image: redis:7
    container_name: controlacontas_cache
    ports:
    - 6379:6379

  email:
    image: mailhog/mailhog:v1.0.0
    container_name: controlacontas_email
    ports:
      - "8025:8025"
