[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120
known_first_party = [
    "controlacontas",
    "config",
]
skip = [".venv/"]
skip_glob = ["**/migrations/*.py"]
